language : node_js

node_js:
  -  "18"

script:
  - npm config set progress false --global
  - npm install
  - npm test
  - npm run build

deploy:
  provider: surge
  skip_cleanup: true
  domain: http://clockapp.surge.sh/
  project: ./build/

on:
  branch: master
